version: '3.7'

services:
  paycash_postgres:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    logging:
      driver: none

  paycash_rabbitmq:
    image: rabbitmq:3.8.9-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    logging:
      driver: none

  paycash_django:
    build: ./
    volumes:
      - ./src:/src:rw
      - ./.env:/src/core/.env
    depends_on:
      - paycash_postgres
    ports:
      - 8000:8000
    environment:
      PROCESS: DEV_DJANGO
      test: "pytest -v --cov . --cov-report term-missing
      --cov-fail-under=100 --flake8 --mypy -n 4 --no-migrations
      --reuse-db -W error
      -W ignore::django.utils.deprecation.RemovedInDjango40Warning"
      makemigrations: python manage.py makemigrations
      migrate: python manage.py migrate
      squashmigrations: python manage.py squashmigrations
      makemessages: python manage.py makemessages --all
      compilemessages: python manage.py compilemessages
      outdated: pip list --outdated --format=columns
      bandit: bandit -r . --exclude tests
      safety: safety check
      mypy: mypy .
      flake8: flake8 .
      check: python manage.py check --deploy
      shell: python manage.py shell_plus

  paycash_celery:
    build: ./
    volumes:
      - ./src:/src:rw
      - ./.env:/src/core/.env
    depends_on:
      - paycash_postgres
      - paycash_rabbitmq
    environment:
      PROCESS: DEV_CELERY

volumes:
  postgres_data:
  portainer_data: