# Generated by Django 3.1.6 on 2021-03-31 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created_at', verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='modified_at', verbose_name='modified_at')),
                ('name', models.TextField(help_text='name', verbose_name='name')),
                ('users', models.ManyToManyField(blank=True, help_text='user', related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'db_table': 'common.companies',
            },
        ),
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'global_configuration',
                'verbose_name_plural': 'global_configurations',
                'db_table': 'reference.global_configurations',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='created_at', verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='modified_at', verbose_name='modified_at')),
                ('position', models.TextField(blank=True, verbose_name='position')),
                ('department', models.TextField(blank=True, verbose_name='department')),
                ('company', models.ForeignKey(help_text='company', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.company', verbose_name='company')),
                ('user', models.OneToOneField(help_text='user', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'db_table': 'common.profiles',
            },
        ),
    ]
